# Generated by Django 4.2.4 on 2023-08-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_mobilephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilephone',
            name='category',
        ),
    ]
